report: ExoMars2020.tex references.bib
	xelatex ExoMars2020.tex -synctex=1 -interaction=nonstopmode --enable-write18
	bibtex ExoMars2020.aux
	xelatex ExoMars2020.tex -synctex=1 -interaction=nonstopmode --enable-write18
	xelatex ExoMars2020.tex -synctex=1 -interaction=nonstopmode --enable-write18